return {
	-- {
	-- 	"yetone/avante.nvim",
	-- 	event = "VeryLazy",
	-- 	lazy = false,
	-- 	version = false,
	-- 	build = "make BUILD_FROM_SOURCE=true",
	-- 	opts = {
	-- 		provider = "ollama",
	-- 		vendors = {
	-- 			ollama = {
	-- 				api_key_name = false,
	-- 				-- endpoint = "127.0.0.1:11434/v1",
	-- 				endpoint = "127.0.0.1:5000/v1",
	-- 				model = "gemma2:2b",
	-- 				-- model = "hf.co/TheBloke/dolphin-2.6-mistral-7B-dpo-laser-GGUF:dolphin-2.6-mistral-7b-dpo-laser.Q4_K_M.gguf",
	-- 				-- model = "llama3.2:latest",
	-- 				parse_curl_args = function(opts, code_opts)
	-- 					return {
	-- 						url = opts.endpoint .. "/chat/completions",
	-- 						headers = {
	-- 							["Accept"] = "application/json",
	-- 							["Content-Type"] = "application/json",
	-- 						},
	-- 						body = {
	-- 							model = opts.model,
	-- 							messages = require("avante.providers").openai.parse_messages(
	-- 								code_opts
	-- 							), -- you can make your own message, but this is very advanced
	-- 							max_tokens = 2048,
	-- 							stream = true,
	-- 						},
	-- 					}
	-- 				end,
	-- 				parse_response_data = function(
	-- 					data_stream,
	-- 					event_state,
	-- 					opts
	-- 				)
	-- 					require("avante.providers").openai.parse_response(
	-- 						data_stream,
	-- 						event_state,
	-- 						opts
	-- 					)
	-- 				end,
	-- 			},
	-- 		},
	-- 		-- behavior = {
	-- 		-- 	auto_suggestions = true,
	-- 		-- },
	-- 		mappings = {
	-- 			ask = "<leader>ua", -- ask
	-- 			edit = "<leader>ue", -- edit
	-- 			refresh = "<leader>ur", -- refresh
	-- 		},
	-- 		-- hints = {
	-- 		-- 	enabled = false,
	-- 		-- },
	-- 	},
	-- 	dependencies = {
	-- 		"nvim-treesitter/nvim-treesitter",
	-- 		"stevearc/dressing.nvim",
	-- 		"nvim-lua/plenary.nvim",
	-- 		"MunifTanjim/nui.nvim",
	-- 		--- The below dependencies are optional,
	-- 		"nvim-tree/nvim-web-devicons", -- or echasnovski/mini.icons
	-- 		-- "zbirenbaum/copilot.lua", -- for providers='copilot'
	-- 		{
	-- 			-- support for image pasting
	-- 			"HakonHarnes/img-clip.nvim",
	-- 			event = "VeryLazy",
	-- 			opts = {
	-- 				-- recommended settings
	-- 				default = {
	-- 					embed_image_as_base64 = false,
	-- 					prompt_for_file_name = false,
	-- 					drag_and_drop = {
	-- 						insert_mode = true,
	-- 					},
	-- 					-- required for Windows users
	-- 					use_absolute_path = true,
	-- 				},
	-- 			},
	-- 		},
	-- 		{
	-- 			-- Make sure to setup it properly if you have lazy=true
	-- 			"MeanderingProgrammer/render-markdown.nvim",
	-- 			opts = {
	-- 				file_types = { "markdown", "Avante" },
	-- 			},
	-- 			ft = { "markdown", "Avante" },
	-- 		},
	-- 	},
	-- },
	-- {
	-- 	"dlants/magenta.nvim",
	-- 	lazy = false, -- you could also bind to <leader>mt
	-- 	build = "npm install --frozen-lockfile",
	-- 	opts = {},
	-- },
	-- llama.vim is blocking on input so it makes it really hard to use like this
	-- {
	-- 	-- "ggml-org/llama.vim",
	-- 	dir = "~/code/others/llama.vim",
	--
	-- 	-- "pnb/llama.vim",
	-- 	config = function()
	-- 		local llama_config = vim.g.llama_config
	-- 		llama_config.show_info = 0
	-- 		llama_config.keymap_trigger = "<C-F>"
	-- 		llama_config.keymap_accept_full = "<C-k>"
	-- 		llama_config.keymap_accept_line = "<C-l>"
	-- 		llama_config.keymap_accept_word = "<C-B>"
	-- 		llama_config.keymap_debug_toggle = "<leader>lld"
	-- 		vim.g.llama_config = llama_config
	-- 	end,
	-- },
	-- {
	-- 	"ggml-org/llama.vim",
	-- },
}
