alias ..='cd ..'
alias ...='cd ../..'
alias l='ls -lah'
alias la='ls -AF'
alias ll='ls -lFh'

alias rmswp='find . -name "*.swp" -type f | xargs rm -f'

alias gst='git status'
alias gl='git log'
alias gf='git fetch'
alias gb='git branch'
alias gd='git diff'
alias ga='git add'
alias gc='git commit -m'
alias gca='git commit -am'
alias gcam='git commit --amend'
alias gri='git rebase --interactive'
alias gdc='git svn dcommit'

alias ss='script/server'
alias sc='script/console'
