for config_file ($ZSH/lib/*.zsh) source $config_file
for config_file ($ZSH/concerns/**/*.zsh) source $config_file

setopt AUTO_CD
setopt CORRECT
setopt CORRECTALL
setopt COMPLETE_IN_WORD
setopt ALWAYS_TO_END
setopt PROMPT_SUBST #We will also use the expansions-in-prompt feature
setopt INTERACTIVE_COMMENTS

unsetopt MENU_COMPLETE
setopt AUTO_MENU

setopt HIST_IGNORE_DUPS
setopt HIST_FIND_NO_DUPS
setopt SHARE_HISTORY
setopt HIST_IGNORE_SPACE
setopt APPEND_HISTORY
setopt EXTENDED_HISTORY
setopt HIST_REDUCE_BLANKS

HISTFILE=~/.zsh_history
SAVEHIST=5000
HISTSIZE=5000

REPORTTIME=10
LISTMAX=0

autoload url-quote-magic
zle -N self-insert url-quote-magic

bindkey -v
