[main]
font=AkkuratMono Nerd Font:size=16
box-drawings-uses-font-glyphs=yes

[key-bindings]
scrollback-up-page=Mod1+u
scrollback-down-page=Mod1+d

clipboard-copy=Mod1+c
clipboard-paste=Mod1+v

# [colors]
# foreground=ffffff
# background=111111

[colors-dark]
background = 09090a
foreground = ffffff

# Normal colors
regular0 = 1a1e1d
regular1 = dbabeb
regular2 = 62d196
regular3 = 7fa7af
regular4 = 64629f
regular5 = 5f4c65
regular6 = a9d1df
regular7 = f0f4ef

# Bright colors
bright0 = 5d6f74
bright1 = d95490
bright2 = 63b0b0
bright3 = c0c0dd
bright4 = 5786bc
bright5 = 3f3442
bright6 = 849da2
bright7 = f5f4ef
